name: BMI Calculator CI

# Triggers the workflow on push or pull request events to the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3  # Checks out your repository under $GITHUB_WORKSPACE

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8  # Sets up Python 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrades pip
        pip install pytest  # Installs pytest

    - name: Run tests
      run: |
        pytest  # Runs pytest to execute unit tests
