name: CI Workflow

on:
  push:
    branches: 
      - main
      - lab2
  pull_request:
    branches: 
      - main
      - lab2

permissions:
  contents: write  
  packages: write
  actions: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.versioning.outputs.new_version }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Calculate next version
        id: versioning
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch
          release_branches: main,lab2
          create_annotated_tag: true

      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag ghcr.io/${{ github.repository }}/bmicalculator:${{ steps.versioning.outputs.new_version }}

      - name: Push the Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/bmicalculator:${{ steps.versioning.outputs.new_version }}
          docker tag ghcr.io/${{ github.repository }}/bmicalculator:${{ steps.versioning.outputs.new_version }} ghcr.io/${{ github.repository }}/bmicalculator:latest
          docker push ghcr.io/${{ github.repository }}/bmicalculator:latest

      - name: Run Container Structure Tests
        uses: docker://gcr.io/gcp-runtimes/container-structure-test:latest
        with:
          args: 'test --image ghcr.io/${{ github.repository }}/bmicalculator:${{ steps.versioning.outputs.new_version }} --config container_test.yml'

  release:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.build-and-test.outputs.new_version }}
          release_name: Release v${{ needs.build-and-test.outputs.new_version }}
          draft: false
          prerelease: false
